
server {
  listen 80;
  server_name gochred.github.io;

  root "/path/to/project_folder"; # Change path to folder with downloaded source
  index index.html;

  access_log off;
  autoindex off;
  charset utf-8;

  location /fam {
    if (-f $request_filename ) {
      break;
    }

    if ($args ~ "_escaped_fragment_") {
      rewrite ^/fam/(.+)/$ /snippets/$1.html last;
      rewrite ^/fam/([.a-zA-Z0-9-_/]+)$ /snippets/$1.html last;
      rewrite ^/fam/ /snippets/1.html last;
    }

    location = /fam {
      if ($args ~ "_escaped_fragment_") {
        rewrite ^/fam /fam/snippets/1.html last;
      }

      
      return 301 /fam/;
      
    }

    rewrite ^/fam/?$ /fam/index.html last;
    rewrite ^/fam/[.a-zA-Z0-9-_]+(/(.*))? /fam/$2 last;

    try_files $uri $uri/;
  }
}
